name: recqc
channels:
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib>=3.9,<4
  - numpy>=2,<3
  - openpyxl>=3.1
  - pandas>=2.2,<3
  - pillow>=10.4,<12
  - rdkit>=2024.9
  - tqdm>=4.66,<5
